const skills = [
  {
    id: 1,
    category: "Languages",
    short: "Languages",
    level: 90,
    blurb: "Strongly typed, modern JavaScript at the core with Java and C for fundamentals.",
    items: [
      { name: "JavaScript (ES6+)", level: 95 },
      { name: "TypeScript", level: 85 },
      { name: "Java", level: 75 },
      { name: "C", level: 70 },
      { name: "HTML5", level: 95 },
      { name: "CSS3", level: 92 },
    ],
  },
  {
    id: 2,
    category: "Frontend",
    short: "Frontend",
    level: 95,
    blurb: "Interface work is home turf: component systems, motion and accessible markup.",
    items: [
      { name: "React.js", level: 95 },
      { name: "Next.js", level: 88 },
      { name: "Tailwind CSS", level: 94 },
      { name: "GSAP", level: 85 },
      { name: "Responsive UI/UX", level: 92 },
      { name: "REST API Integration", level: 90 },
      { name: "Web Accessibility", level: 80 },
    ],
  },
  {
    id: 3,
    category: "Backend",
    short: "Backend",
    level: 85,
    blurb: "Node services with real auth, real payments and APIs shaped for the client.",
    items: [
      { name: "Node.js", level: 90 },
      { name: "Express.js", level: 88 },
      { name: "RESTful APIs", level: 90 },
      { name: "Authentication & JWT", level: 82 },
      { name: "Payment Gateway Integration", level: 78 },
    ],
  },
  {
    id: 4,
    category: "Cloud & DevOps",
    short: "Cloud / DevOps",
    level: 75,
    blurb: "Containerised deploys, infrastructure as code and pipelines that ship on merge.",
    items: [
      { name: "Docker", level: 85 },
      { name: "Kubernetes", level: 68 },
      { name: "AWS", level: 75 },
      { name: "Google Cloud (GCP)", level: 72 },
      { name: "Terraform", level: 65 },
      { name: "CI/CD Pipelines", level: 80 },
      { name: "Container Optimisation", level: 74 },
    ],
  },
  {
    id: 5,
    category: "Databases",
    short: "Databases",
    level: 80,
    blurb: "Schemas designed up front, so queries stay cheap as the product grows.",
    items: [
      { name: "MongoDB", level: 88 },
      { name: "MySQL", level: 78 },
      { name: "Prisma", level: 75 },
      { name: "Mongoose", level: 85 },
      { name: "Schema Design", level: 80 },
    ],
  },
  {
    id: 6,
    category: "SEO, AEO & GEO",
    short: "SEO / AEO",
    level: 78,
    blurb: "Built to be found by search engines and by the answer engines replacing them.",
    items: [
      { name: "Technical SEO", level: 85 },
      { name: "Answer Engine Optimization (AEO)", level: 78 },
      { name: "Generative Engine Optimization (GEO)", level: 72 },
      { name: "Structured Data / Schema.org", level: 82 },
      { name: "Core Web Vitals", level: 80 },
      { name: "Keyword Strategy", level: 75 },
    ],
  },
  {
    id: 7,
    category: "Tools & Practices",
    short: "Tools",
    level: 88,
    blurb: "The habits around the code: reviews, small commits and clear client comms.",
    items: [
      { name: "Git", level: 92 },
      { name: "npm", level: 90 },
      { name: "Bun", level: 78 },
      { name: "Agile Collaboration", level: 85 },
      { name: "Client Management", level: 88 },
      { name: "Code Review", level: 86 },
    ],
  },
];

export default skills;
